### PR TITLE
linked slides on landing page to edit page

### PR DESCRIPTION
**Pull request by ethanmichel0**

### CODE REVIEW

**Comment by ethanmichel0** [comment]
> When we are a guest, we are taken to a page of errors. I would probably not link for a guest, or you could link to just the slide view.

Resolving now, new commit takes guest to view slide page, not edit page as you suggested.

**Comment by Sammidysam** [comment]
Great!  Bug update: it seems that these changes make the arrows to traverse the carousel no longer work.  Could you check that out?  I also now think it might make sense to not link slides at all if an admin, as it is hard to navigate away from that page.  But I guess I would leave it to be your call there.

**Comment by ethanmichel0** [comment]
> Great! Bug update: it seems that these changes make the arrows to traverse the carousel no longer work. Could you check that out? I also now think it might make sense to not link slides at all if an admin, as it is hard to navigate away from that page. But I guess I would leave it to be your call there.

Thanks for pointing this out. That was stupid. Your point about not being able to navigate away if accidentally clicked on is a good point and I am wondering if it is not worth it to have this feature at all. Deena requested this so that she could have immediate access to editing slides, but I believe she is an admin?

**Comment by Sammidysam** [comment]
No need to call it stupid!  You can just only make it a link if the current user is an admin.  Just make sure the arrows still work, I'd say.

**Comment by ethanmichel0** [comment]
> No need to call it stupid! You can just only make it a link if the current user is an admin. Just make sure the arrows still work, I'd say.

The new update I just did works with the arrows and the time play. The xslt code is kind of ugly (just repetitive) but I think it should be fine hopefully!

**Comment by ethanmichel0** [comment]
> No need to call it stupid! You can just only make it a link if the current user is an admin. Just make sure the arrows still work, I'd say.

When you get a chance, could you test this out on your browser? I am not sure if I am crazy or not but the one thing is that it seems like the slides are taking a bit longer to load for some reason, but this could just be my computer which has been slow today. Does the same thing happen on your browser?

**Comment by Sammidysam** [comment]
Works great!  I don't think any slow down is critical enough to matter too much - everything is usually faster in production anyway.  Merge if you feel like it, otherwise feel free to make it less repetitive, I just recognize that the overall codebase is really repetitive so it's no big deal.

**Comment by ethanmichel0** [comment]
> Now, the `div class="carousel-item"` could also be a template...

That probably would've been smarter, but I think I'll save that for the future haha, I am kind of fried with xslt right now

**Pull request merged**
