### PR TITLE
Allow putting potential content categories into quotes and store if quotes will display quotation marks or not

### PR DESCRIPTION
**Pull request by Sammidysam**
Refactoring is much less of a goal here, so I largely seek to create this pull request as an attempt of a review of that there are no bugs / copying and pasting errors to your knowledge.  I might refactor this some more while the pull request is being reviewed.

### CODE REVIEW

**Comment by Sammidysam** [comment]
This can still be reviewed, but apparently the size of the content category collection is always supposed to be > 0.  This will be added, probably before the pull request is merged.

**Comment by jeremyfifty9** [comment]
if it works -- looks good to me.

**Comment by Sammidysam** [comment]
The validation is done, but I am putting the `quotation-marks` branch into this pull request too.  It is weird to work on quotes in two separate branches at the same time.

**Comment by Sammidysam** [comment]
This branch got very out of control; I did a bad job of keeping it specific to one task.  I'm going to merge it then do better with new branches.

**Pull request merged**
