### PR TITLE
Port provided by an environment variable from db.config -> run.sh

### PR DESCRIPTION
**Pull request by Sammidysam**
Trello: https://trello.com/c/Hvdw80gn/62-community-voices-accept-a-port-provided-in-an-environment-variable

@Terf This should allow the QA instance of Community Voices to actually work.  Could you use this branch to try it?  If it works, we can merge this.

### CODE REVIEW

**Comment by Sammidysam** [comment]
Note: you'll need to add the desired port to your relevant `db.config` file.

**Comment by Terf** [comment]
Looks like it worked, I just rebuilt the QA container from this branch: https://qa.communityhub.cloud/community-voices (note QA currently using empty db). Not sure why the Travis tests failed? Otherwise looks ready to merge. For the new port value in the `db.config` what connection are the rest of those credentials referencing? I think the db is still hosted on ED servers so let's just continue to use that until I move it to CH servers at which point you can use the ED-hosted db just for testing/reference it in `run.sh` (which is not a script used to run anything in production).

**Comment by Sammidysam** [comment]
@Terf On why the Travis tests are failing, `migrate/defaults.sql` has some outdated table columns.  For example, `media_filename` no longer exists within a ContentCategory.  I was wondering, do you still want there to be these defaults?  I kind of prefer a blank database over forcing our content categories on new users, but maybe it's best to start with something?

**Comment by Sammidysam** [comment]
@Terf Community Voices unfortunately still does all development on production.  It is my goal to change this eventually.  So that is referencing the ED database.

**Comment by Sammidysam** [comment]
@Terf I talked to @rehannan about defaults and we are going to make some brand new defaults.  So there is a new card made for that and I guess we need to make and merge that pull request before this one is ready to go.

**Comment by Sammidysam** [comment]
@Terf @rehannan Are we not worrying about the defaults before merging this because they're already tracked in another place? We aren't just letting that slip by, right?

**Pull request merged**
