### PR TITLE
Require explicitly requesting defaults to be filled in on edit

### PR DESCRIPTION
**Pull request by Sammidysam**
Whew, default post requests are gross!

### CODE REVIEW

**Comment by ethanmichel0** [comment]
Hi Sam, so I ran this and it fixed the problem! Just for clarification, how does this change things? It looks like getFormAttributes() is being called with $setDefaults always to true. The logic on line 33 seems to be identical to me, where $default is set to either "$value" or "null"  in the same cases as before due to (a && true) being logically equivalent to (a).

**Comment by Sammidysam** [comment]
Not all requests go to the website layer.  In the case of the checkbox to approve a quote, it is an AJAX request that goes straight to the API.  In this case `$useDefaults` will not be set to true.  Basically, I was defining different behavior for requests to the API versus requests from the website.  Does that make sense?

**Comment by ethanmichel0** [comment]
I think that makes sense. I am a little confused specifically about how error checking works with all of the layers in general, but I think I see why you did that. I'll ask you specifically tomorrow or when it comes up with the work specifically. But basically because $useDefaults will not be true, the variable $default will be set to null which will allow $requestAttributes(content-category) to be null instead of causing an error

**Comment by Sammidysam** [comment]
Not quite `null`, but rather that the variable will be unset.  Quotes had a bit of refactoring that no other model had since I worked with quotes and not the other models.  I like a system for editing on the API side where an object containing each property to be modified is included.  So, that means to only edit approval, you could send `{approved: true}` as your POST body.  If we set defaults with a post body like that, we suddenly set many more items in the quote than we intend to.  Defaults do make sense from the website view, where every field that can be edited is in front of you, so we need to directly specify all fields and not leave certain fields empty.

Anyway, do you have further questions before I merge this, or should I go ahead and merge?

**Comment by ethanmichel0** [comment]
Sorry! I didn't think that you were waiting to merge since I already approved. Hope the questions didn't slow you down. But yeah, you can merge

**Comment by Sammidysam** [comment]
No worries Ethan, I did not see this as a crucial bug or else I would have merged it even with the questions.  Good to ask about that all, and I held off on merging just since I was not in a rush.  Will merge now.

**Pull request merged**
