### PR TITLE
Lowers max-height of content-category image

### PR DESCRIPTION
**Pull request by acrap5**
This PR is a quick fix to content category images overlapping text on slides. Max-height for said images was changed to 16vh as suggested by @Sammidysam.

https://www.notion.so/John-sent-an-email-about-text-overlap-and-remove-that-overlap-10e5869194bc4105b3b1b9f4b2a28060

### CODE REVIEW

**Review by Sammidysam — APPROVED** [review]
Did not run to officially test, but the code seems like it will do the job.

**Comment by acrap5** [comment]
This is totally my bad, realized after the meeting today I never actually pushed these changes. From a visual standpoint though this has been approved by John and Rowan so as long as it looks good to you, should be fine to go.

**Comment by Sammidysam** [comment]
Sounds good.  I will review it tonight.

**Review by Sammidysam — CHANGES_REQUESTED** [review]
No reason for me to test this code if John and Rowan approved it already.  I don't have any hard opinions about this.  However, I am requesting changes because I only see this changed in JavaScript and not the other places.  What about the slide view?  I think this will only affect the JavaScript slide preview, no?

**Comment by acrap5** [comment]
You're totally right, thanks for the catch.

**Review by Sammidysam — APPROVED** [review]
I would also do a quick project Ctrl+F just to make sure there isn't a third rendering spot, but I believe these two are the only spots.

Is there no plan for having `font_size` as part of the slide in the future?  This change works for cases beyond just the previous bad one, right?  Assuming yes.

**Comment by acrap5** [comment]
Can confirm that these are the only two rendering spots. Yes this fix works beyond the one particular one that prompted this.

**Review by Sammidysam — APPROVED** [review]

**Pull request merged**
