### PR TITLE
Make building / running the local server insanely easy

### PR DESCRIPTION
**Pull request by Sammidysam**
I apologize as this is not really the highest priority right now, but I figured if I was spending all this time figuring out how to run locally I might as well make no one in the future ever have to.

Just wondering if the general restructuring of the Dockerfile is fine for you all?

Composer seems to install from the lock file rather than from the JSON file - should I seek to avoid that so that it rather pulls the latest?  Maybe run install then update? (initially it did update then install but this caused problems)

Is it worth restructuring the `init.sh` script now that we are not hackily putting everything into a single line of code?

### CODE REVIEW

**Comment by Terf** [comment]
Ok so a few (small) things I’d change about that Dockerfile:

Why did you add extra `ADD` commands? `ADD . /var/www/html` moves everything into the container, so `ADD ./build/init.sh /init.sh` and `ADD ./build/composer-install.sh /composer-install.sh` is creating duplicate files and also increasing the number of layers in the final container (not a huge deal but see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers). I think it’d be better to remove these `ADD` commands and just run the install scripts from /var/www/html.

Also if you keep the install scripts in /var/www/html instead of moving them to root, you don’t need to `cd` at the top of the init.sh script (though explicitly doing this might make it more clear we need to be in /var/www/html)

You run init.sh with the command `bash init.sh` but the shebang at the top of the script is `#!/bin/sh`, so it’s not super clear whether this is a shell script or bash script (and there are some important differences — I believe `if [[ condition ]]` works in bash while only `if [ condition ]` works in the standard shell). Personally I think it’s better practice to not invoke the shell on the command line at all, just run ./init.sh and rely on the shebang for indicating the intended shell. Unless you think there’s a good reason for using `bash ./init.sh`, I’d like to change that

**Comment by Sammidysam** [comment]
Thank you so much for the feedback, Tim!

So, the multiple ADD comments were purely from me having no experience previously with Docker.  I agree that it is superfluous and I will remove those and correspondingly run the scripts from `/var/www/html` next time I edit this.

I agree with `cd` then not being needed but good to have to display what our `pwd` needs to be, so I think I will comment it and mention our necessary working directory.

I agree that the shebang doesn't line up - what happened there is that for the `.sh` files in `build`, they are not marked as executable so I could not run them through the Shebang unless they were previously marked as executable.  What I realize now is that I think marking them as executable before sending them to the container will maintaining that access right, so I will try for that.

I do think, though, that we might as well use Bash rather than Shell.  I'll just change the Shebang.  I don't see a reason to use a lower-level language for actions this trivial (in terms of speed).

**Comment by Sammidysam** [comment]
I'm also still wondering about the two questions at the end of my initial pull request comment if you have any opinions about those!  Thanks again

**Comment by Terf** [comment]
Sounds good. Idk much about composer so I don't have anything to say about that. Feel free to restructure any files. With the `init.sh` specifically I think breaking massive one-liner into multiple lines is a good idea but I'd keep things that depend on each other on the same line, chained with `&&` (which only executes the next command if the previous one executed successfully). So I'd keep `INI_LOC=`php -i | grep 'Loaded Configuration File => ' | sed 's/Loaded Configuration File => //g' | sed 's/cli/apache2/g'` && \
  sed -ie 's/upload_max_filesize = 2M/upload_max_filesize = 64M/g' "$INI_LOC" && \
  sed -ie 's/post_max_size = 8M/post_max_size = 512M/g' "$INI_LOC"` on one line and `curl -sS https://getcomposer.org/installer -o composer-setup.php && \
  php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
  php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
  composer update && composer install` one one line

**Comment by Sammidysam** [comment]
I think all other changes mentioned are now implemented.  Ready to merge whenever you are! :shipit:

**Comment by jeremyfifty9** [comment]
this looks good

**Pull request merged**
