### PR TITLE
Removed deprecated screen listing on slide creation/update screen

### PR DESCRIPTION
**Pull request by acrap5**
This small change gets rid of the deprecated screen listing from the slide creation and slide update pages.

https://www.notion.so/Remove-deprecated-screen-listing-on-create-a-slide-170c6aabf83245fc86f85b2c1d41a5ea

### CODE REVIEW

**Review by Sammidysam — CHANGES_REQUESTED** [review]
While we are at it, we might as well delete the database table itself too, no?  Did John and Rowan say they want it to remain?

Can check out the migrate folder for instructions on migrations.

**Comment by acrap5** [comment]
Yes I was thinking the same (John and Rowan did not say anything about wanting it to remain), I just wasn't sure if I had the ability/authority to do so.

**Comment by acrap5** [comment]
Is it necessary to write a migration script to do so? Almost feels like it'd be just as easy to do manually.

**Comment by Sammidysam** [comment]
Can you check with John and Rowan that they don't need the legacy data to remain?

Need to use a migration so that we can not have to redo the SQL across databases over history.

**Review by Sammidysam — CHANGES_REQUESTED** [review]
Might as well remove the Locations page (`/locations`) as a whole too then, no?

**Comment by Sammidysam** [comment]
Also do deal with these merge conflicts - sorry that we merged the migration system through Ethan's batch upload PR.

**Comment by acrap5** [comment]
I believe I've removed all the code that should be, but please let me know if you think I missed something or made a mistake in removing code that's still needed.

**Review by Sammidysam — CHANGES_REQUESTED** [review]
Not quite - `schema.sql` should not be modified directly - it is generated by the migration script (at the end of each migration it will regenerate the file).  The correct way here to delete the tables is to write a SQL migration that will execute the SQL code to delete the tables.  At the end of that, the migration script will update `schema.sql` appropriately.  Let me know if that is confusing.

Also, do remember to reserve merge conflicts before we move too far with this.

**Comment by acrap5** [comment]
I already wrote a migration script to do so, it is earlier in this PR. So I'll undo the manual changes to `schema.sql` and this should be good to go?

**Comment by Sammidysam** [comment]
Ah, my bad!  This issue keeps being dragged along a bit further so I am not good at holding onto the context I need to.  It is good that we will generate changes in `schema.sql`, but we need to do so through a command.  That command is run at the end of every migration in the main branch - see https://github.com/EnvironmentalDashboard/community-voices/blob/master/migrate/migrate.php#L25-L26.  If you run it manually, then you should be good to go.  I think I will still need to test this after, but that should be quick.

Also, reminder about the merge conflicts I see.

**Comment by acrap5** [comment]
Merging that one command from master into the `migrate.php` script on this branch should fix the issue no? We'll just need to run the script once we merge this branch into master and then everything should be as it should be, right?

**Comment by Sammidysam** [comment]
@acrap5 Are you okay with running the command at the end of the migrate script alone to update `schema.sql`?  I would prefer an updated `schema.sql` gets uploaded with these changes.

**Comment by acrap5** [comment]
Done

**Pull request merged**
