### PR TITLE
Batch Upload

### PR DESCRIPTION
**Pull request by ethanmichel0**
Now quotation marks can be set to false/ the box on front end can be unchecked and this won't throw a PDO error. For some reason MYSQL doesn't interpret 0 as false. Note that boolval(intval(x)) is required instead of just intval(x) because intval(x) will always give 0.

### CODE REVIEW

**Comment by Sammidysam** [comment]
If my review blocks you in any way, please let me know and I can expedite it.

**Comment by ethanmichel0** [comment]
> If my review blocks you in any way, please let me know and I can expedite it.

@Sammidysam Hey man! So I don't think that this should hold me up too much. This should be a super easy review on your end hopefully though. I only had to change one line. Also I tested this to see that both cases work (i.e. quotationMarks has a value and quotationMarks doesn't have a value and both of these work. Note my comment above that intval("string") will always return 0 so instead intval(boolval("string")) is needed here instead.

**Comment by Sammidysam** [comment]
Did you merge the batch upload branch into here?  So this is now a PR of the batch upload branch?

**Comment by Sammidysam** [comment]
Seems so.  Please update the description / title of this accordingly and I can try to code review this evening.

**Pull request closed without merging**
